import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "../providers";
import UserProvider from "../context/UserProvider";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { ThemeProvider } from "../context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
  ...props
}: {
  children: React.ReactNode;
}) {

  return (
    <ThemeProvider>
      <html lang="en" className="">
        <body className={inter.className}>
          <main>
            <UserProvider>{children}</UserProvider>
          </main>
        </body>
      </html>
    </ThemeProvider>
  );
}
